CREATE TABLE [USER] (
	ID int NOT NULL,
	USERNAME varchar(15) NOT NULL UNIQUE,
	PASSWORD varchar(64) NOT NULL,
	REGISTRATION_DATE smalldatetime NOT NULL,
  CONSTRAINT [PK_USER] PRIMARY KEY CLUSTERED
  (
  [ID] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [MIGRATION] (
	ID int NOT NULL,
	USER_ID int NOT NULL,
	DATE smalldatetime NOT NULL,
	FROM_SERVICE_ID int NOT NULL,
	TO_SERVICE_ID int NOT NULL,
	MIGRATION_TYPE_ID int NOT NULL,
	ITEMS_COUNT int NOT NULL,
  CONSTRAINT [PK_MIGRATION] PRIMARY KEY CLUSTERED
  (
  [ID] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [SERVICE] (
	ID int NOT NULL,
	NAME varchar(25) NOT NULL UNIQUE,
  CONSTRAINT [PK_SERVICE] PRIMARY KEY CLUSTERED
  (
  [ID] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [MIGRATION_TYPE] (
	ID int NOT NULL,
	TYPE varchar(25) NOT NULL UNIQUE,
  CONSTRAINT [PK_MIGRATION_TYPE] PRIMARY KEY CLUSTERED
  (
  [ID] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [TOKEN] (
	ID int NOT NULL,
	USER_ID int NOT NULL,
	TOKEN varchar(100) NOT NULL,
	SERVICE_ID int NOT NULL,
  CONSTRAINT [PK_TOKEN] PRIMARY KEY CLUSTERED
  (
  [ID] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO

ALTER TABLE [MIGRATION] WITH CHECK ADD CONSTRAINT [MIGRATION_fk0] FOREIGN KEY ([USER_ID]) REFERENCES [USER]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [MIGRATION] CHECK CONSTRAINT [MIGRATION_fk0]
GO
ALTER TABLE [MIGRATION] WITH CHECK ADD CONSTRAINT [MIGRATION_fk1] FOREIGN KEY ([FROM_SERVICE_ID]) REFERENCES [SERVICE]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [MIGRATION] CHECK CONSTRAINT [MIGRATION_fk1]
GO
ALTER TABLE [MIGRATION] WITH CHECK ADD CONSTRAINT [MIGRATION_fk2] FOREIGN KEY ([TO_SERVICE_ID]) REFERENCES [SERVICE]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [MIGRATION] CHECK CONSTRAINT [MIGRATION_fk2]
GO
ALTER TABLE [MIGRATION] WITH CHECK ADD CONSTRAINT [MIGRATION_fk3] FOREIGN KEY ([MIGRATION_TYPE_ID]) REFERENCES [MIGRATION_TYPE]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [MIGRATION] CHECK CONSTRAINT [MIGRATION_fk3]
GO



ALTER TABLE [TOKEN] WITH CHECK ADD CONSTRAINT [TOKEN_fk0] FOREIGN KEY ([USER_ID]) REFERENCES [USER]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [TOKEN] CHECK CONSTRAINT [TOKEN_fk0]
GO
ALTER TABLE [TOKEN] WITH CHECK ADD CONSTRAINT [TOKEN_fk1] FOREIGN KEY ([SERVICE_ID]) REFERENCES [SERVICE]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [TOKEN] CHECK CONSTRAINT [TOKEN_fk1]
GO

